package io.coupling.git.data.mining.repo;

final class GitLogException extends RuntimeException {

  GitLogException(final Throwable cause) {
    super(cause);
  }
}
